### ISSUE TITLE
Add a link to Awesome README repo to "More Resources" or "Let it Fly" chapter

### ISSUE THREAD

**Issue by smartapant** [CatchTheTornado/opensourcetipsbook#3]
In the "Let it Fly" chapter, you highlighted the significance of a readme and its essential sections. This is indeed crucial for open-source projects on GitHub.

[Matias Singers](https://github.com/matiassingers) has curated the [Awesome README](https://github.com/matiassingers/awesome-readme) list, which includes helpful examples, useful tools, and informative articles. I believe referencing this repository would be valuable, either in the "More Resources" chapter or within the readme instructions of the "Let it Fly" chapter.

**Comment by pkarw** [comment]
Perfect, definitely worth adding!

**Comment by smartapant** [comment]
Will do, thanks!
