### ISSUE TITLE
CC-BY?

### ISSUE THREAD

**Issue by heathermeeker** [CatchTheTornado/opensourcetipsbook#5]
CC-BY would be a better license for text than a software license. Just a suggestion. https://creativecommons.org/licenses/by/4.0/

**Comment by pkarw** [comment]
Hey @heathermeeker! Thanks for the suggestion. Yea, I buy it :) Created #6 and waiting for @filrak approval to merge it

Thanks once again!

**Comment by pkarw** [comment]
... and by the way I saw you specialize in OS law. It's great. Maybe you consider a contribution to this book regarding - extremely important topic: which license to chose and when?

Would be so great to have you as a contributor :) it's open source so what we can offer in exchange is pretty cool credits and eternal fame 😎

Please let me know what do you think @heathermeeker

**Comment by hmeeker** [comment]
I would be happy to contribute. I think this is a great idea. I actually have a license picker here. https://github.com/heathermeeker/license-picker
I am not much of a coder! I wrote it to teach myself modern coding. (I learned to code in FORTRAN!) I am happy to contribute this or work on it if you think it's useful.

**Comment by pkarw** [comment]
Hey @hmeeker I think this is great, please contribute! Would be awesome if you could create a new chapter just about choosing the license - including this visual license picker (but preferably) also some text - how you pick up the license, what kind of traps you should be aware of etc.

**Comment by pkarw** [comment]
@hmeeker not sure but this one could be helpful for you for getting started: https://github.com/CatchTheTornado/opensourcetipsbook#how-to-contribute

**Comment by pkarw** [comment]
solved with #6
